version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=CEBuny95
      - DB_NAME=vivero
    volumes:
      - ./:/app

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: CEBuny95
      MYSQL_DATABASE: vivero
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: